### ISSUE TITLE
Trait "Botble\Payment\Services\Traits\PaymentTrait" not found

### ISSUE THREAD

**Issue by Mahmood-Hussain** [bhattaraisubash/esewa-botble-plugin#1]
![image](https://github.com/bhattaraisubash/esewa-botble-plugin/assets/31275645/eb8a23b6-9a2f-4d7d-97ff-20ff247bbbdf)

I simply downloaded zip, unzipped and put it in plugins folder but when I tried to activate this from dashboard got above error.

**Comment by bhattaraisubash** [comment]
The plugin is compatible with only old version of botble payment plugin. There has been updates in both botble cms and it's plugins. So, you might have to look into it.

**Comment by Mahmood-Hussain** [comment]
Thank you so much for your prompt reply! got it.
